import Head from 'next/head';
import {useUser} from '../hooks';
import {User} from '../interfaces';

const Navbar = () => {
  const {data, isLoading, isError} = useUser();
  const user = data as User;

  let greeting = <></>;

  if (isLoading) greeting = <div>loading...</div>;

  if (isError) greeting = <div>fetch failure</div>;

  if (data)
    greeting = (
      <div>
        Greeting {user.id} - {user.title}
      </div>
    );

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {greeting}
    </>
  );
};

export default Navbar;
